@extends('frontend.layout.applogin')

@section('content')
<div class="aboutus">
	<div class="container">
       <div class="row">
           <div class="col-md-12">
               <h1>Privacy Policy APARTOLINO</h1>
                <!-- p class="wow fadeIn animated" data-wow-duration="2s">Lorem ipsum dolor sit amet</p> -->
           </div>
       </div>
       <div class="row">
           <div class="col-md-12">
               <div class="privacy-policy">
               <p>The protection of your privacy is very important to us. If we collect, process or use personal information from you as part of our offer, this is in accordance with the applicable Swiss and European protective laws.</p>
			   <p>What data does APARTOLINO collect?</p>
			   <p>We use personal information that you provide to us for the execution and use of our offer:</p>

			   <h1>1. By calling and using our site</h1>
				<p>When you access the platform, e.g. Search for accommodation, make listings, make bookings or confirm booking requests, pay for accommodation, comment or review, or communicate with other users or APARTOLINO, we may record data such as your IP address, date and time Visit, the use of our platform, your browser type, and the operating system you use, as well as your visited pages and your home page.</p>
				<p>In addition, when using a mobile device, we collect device and location data. These data are recorded regardless of whether you are registered with APARTOLINO or have logged into your APARTOLINO account.</p>

				<h1>2. After a registration (registration)</h1>
				<p>On our website you have the possibility to set up a personal user account. In your user account, you can save your personal information and thus either book an offer or book one.</p>
				<p>APARTOLINO requires your e-mail address and a freely selectable password, as well as your address and your first and last name and number data, to set up your personal user account. The e-mail address you provide is also used as an access code for the user account. After successful registration you will automatically receive a confirmation by e-mail. You can update your details at any time in the personal area of ​​your user account.</p>
				<p>How are we collecting data?</p>
				<ul>
					<li>
						<h1>1. Cookies</h1>
						<p>APARTOLINO uses cookies on the website. Cookies are small text files, which are stored in the cache of your browser in order to allow a re-detection of your browser</p>

						<p>We use 'permanent' cookies. They remain on the user's computer to simplify the personalization and registration services the next time you visit our site. Cookies may be e.g. Store what the user has selected. The user can manually remove the cookies at any time.</p>
						<p>In addition, we use 'session cookies'. They do not remain on the user's computer. As soon as the user leaves the page, these temporary cookies are deleted. By collecting the information, we can analyze the usage patterns and structure of the page. In this way we can continually improve our offer, e.g. The content, the personalization or the simplicity of the page.</p>
						<p>Of course, you can also visit our website without cookies on your browser. You can save restrict or disable cookies in your browser settings at any time. However, this may result in limitations to the functionality and user friendliness of our website. In addition, to disable third-party business-to-business advertising, you can simply put a checkmark in the appropriate company's box at www.youronlinechoices.com.</p>
					</li>
					<li>
						<h1>2. Web analysis and tracking</h1>
						<p>Tracking data is used to collect and store data for marketing purposes and optimization of the site. The user may object to this collection and storage at any time for the future.</p>

						<ul>
							<li>
								<h1>A. Google Analytics</h1>
								<p>Our website uses Google Analytics, a web analytics service provided by Google, Inc. ( "Google"). Google Analytics uses cookies. The information generated by the cookie about your use of our website is generally transferred to a Google server in the USA and stored there. However, in the case of the activation of the IP anonymisation on this website, your IP address will be previously abridged by Google within the Member States of the European Union or in other Contracting States of the Agreement on the European Economic Area.</p>
								<p>Only in exceptional cases will the full IP address be transferred to a Google server in the USA and abbreviated there. On behalf of APARTOLINO, Google will use this information to evaluate your use of our website in order to compile reports on the website activities and to provide other services related to the use of the website and the Internet against APARTOLINO. The IP address transmitted by your browser as part of Google Analytics will not be merged with other Google data.</p>
								<p>You can prevent Google's processing of the data (including your IP address) generated by the cookie and your use of the website (including your IP address) as well as the processing of this data by Google by downloading and installing the browser plug-in available under the following link :https://tools.google.com/dlpage/gaoptout?hl=en.</p>
							</li>
							<li>
								<h1>B. Google Adwords</h1>
								<p>We also use Google AdWords online advertising and Google AdWords conversion tracking. Google Conversion Tracking is an analysis service provided by Google Inc. (1600 Amphitheater Parkway, Mountain View, CA 94043, USA, "Google"). When you click a Google-served ad, a conversion tracking cookie is placed on your computer. These cookies lose their validity after 30 days, contain no personal data and thus do not serve for personal identification.</p>
								<p>If you visit certain pages of our website, and the cookie has not expired, Google and we recognize that you have clicked on the ad and forwarded to this page. Each Google AdWords customer receives a different cookie. There is therefore no way that cookies can be tracked through the AdWords website.</p>
								<p>The information obtained through the conversion cookie is used to create conversion statistics for AdWords customers who have opted for conversion tracking. Customers can see the total number of users who clicked on their ad and were redirected to a conversion tracking tag. However, they do not receive any information that allows users to be personally identified.</p>
								<p>If you do not want to participate in tracking, you can disagree with this usage by preventing the installation of the cookies by setting the appropriate settings for your browser software (deactivation option).</p>
								<p>They are not included in the conversion tracking statistics. For more information and Google's privacy policy, please visit: http://www.google.com/policies/technologies/ads/,http://www.google.com/policies/privacy/.</p>
							</li>
						</ul>

					</li>
				</ul>

				<h1>3. Social-Plug-Ins (Facebook Connect)</h1>
				<p>Facebook Connect is a service provided by Facebook, Inc. The use of Facebook Connect is subject to the terms and conditions of use of Facebook.</p>
				<p>When using Facebook Connect, publicly accessible data and Facebook-published data from your Facebook profile will be transferred to our website. Conversely, data can be transferred from our website or via the APARTOLINO app to your Facebook profile. Your data will be stored and processed by APARTOLINO for registration purposes on our platform.</p>
				<p>By registering on our Facebook Connect platform, you agree to the transfer of pro fi les from your Facebook profile to APARTOLINO, as well as the transfer of data to APARTOLINO's use of Facebook.</p>

				<h1>4. Log files</h1>
				<p>With each access to our site, the usage data are transmitted by the respective Internet browser and stored in log files, the so-called server log files.</p>
				<p>We evaluate these logfile records in an anonymous form, in order to improve our offer and make them more user-friendly, to find errors faster and to fix them, and to control server capacities.</p>

				<h1>5. Newsletter</h1>
				<p>If you have agreed to the newsletter, APARTOLINO will use the email address provided by you as part of the setup of your user account to send you information about promotions and offers by APARTOLINO. The contents of the newsletters can thus personalize APARTOLINO in such a way that it contains, in particular, information that APARTOLINO considers particularly interesting to you. APARTOLINO takes account of your booking history, ie the bookings you have made in the past, as well as the offers you have viewed in the past on the website.</p>
				<p>In the personal area of your member account, you can manage the settings for the APARTOLINO newsletter. Of course, you can also unsubscribe from the personal area of your user account as well as the newsletter via the contact form.</p>

				<h1>What do we use your data for?</h1>
				<p>APARTOLINO uses your data,</p>
				<ol>
					<li>to give you access to our platform and its use;</li>
					<li>to operate, protect, improve and optimize our platform. This, for example, through analysis and research, personalization or other individualisation and also for advertising measures;</li>
					<li>to create and maintain a trustworthy and secure environment on our platform and services. In particular through the detection and prevention of fraud, the carrying out of investigations and risk analyzes, the verification of the address given in your advertisements, the data provided by you for identification and comparison with databases;</li>
					<li>to send you news on services and support, as well as administrative messages, reminders, technical notices, updates, safety warnings and information requested by you;
to implement rewards, referral programs, polls, competitions, competitions or other advertising or events sponsored or managed by APARTOLINO or our business partners;</li>
					<li>to comply with our legal obligations in order to resolve legal disputes that may be with one of our users and to enforce our agreements with third parties;</li>
					<li>to send you marketing and advertising, as well as other information that may be of interest to you, including information on APARTOLINO or general advertising campaigns for partner campaigns and services. Of course, only as far as you have agreed to the newsletter. You can unsubscribe from the receipt of such notifications (see Newsletter).</li>
				</ol>

				<h1>Transmission of personal data to third parties</h1>
				<ol>
					<li>We will share your personal information with third parties to complete your booking. For this purpose, the relevant booking information must be sent to the accommodation you have booked. This may include information such as your name, your contact details, your payment details, your specific requests from the booking, as well as the names of the guests traveling with you. This information can be used by APARTOLINO or the accommodation to provide you with individual, booking-related information. If you have a question about your reservation, we may contact the host and ask him to take care of it.</li>
					<li>If necessary, we use third-party service providers, such as data processors, to process your personal data on our behalf. This is done to enable booking payments, to send marketing material or to analytical customer services. These processors are bound by secrecy clauses and are prohibited from using them for their own purposes or for any other purposes.</li>
					<li>We disclose personal data on legal enforcement or against other governmental agencies when required by law or by the authorities or urgently needed to prevent, detect or prosecute criminal offenses.</li>
					<li>We work with business partners around the world to market or promote accommodation and help our business partners to market and advertise their travel services. This may mean that their services are integrated on our website or they have the possibility to offer an individual offer on our website - or we advertise on their website. When you make a booking on a website of our business partners, some personal data will be passed on to you. Some business partners will receive your personal data from us if requested by them. If you make a booking on a website of our business partners, please read the privacy policies of these websites for more information.</li>
				</ol>
				
				<h1>Revocation of consent</h1>
				<p>You may revoke your consent at any time with effect for the future at support@apartolino.ch or by written notification to APARTOLINO GmbH, Zürcherstrasse 137, 8406 Winterthur.</p>
				<p>Information and correction</p>
				<p>You have a right to free information about the data stored about you.</p>
				<p>You may revoke your consent for data collection, processing and use at any time with effect for the future.</p>
				<p>We are at your disposal also for further questions concerning the data protection and the processing of your personal data. APARTOLINO can be reached at the e-mail address support@apartolino.ch. Of course, you can also contact us under the contact details given in the imprint.</p>	
              </div>
          </div>
      </div>
  </div>
</div>

@include('frontend.includes.popups')

@endsection
